server:
  port: 8080
  mode: debug

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: "123456"
  database: online_points_mall
  charset: utf8mb4
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100
