-- BMI 体重追踪系统数据库脚本
-- 创建数据库
CREATE DATABASE IF NOT EXISTS bmi_weight_tracking DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE bmi_weight_tracking;

-- 用户表
CREATE TABLE IF NOT EXISTS user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(100) NOT NULL COMMENT '密码(SHA256)',
    nickname VARCHAR(50) COMMENT '昵称',
    height DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '身高(cm)',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 体重记录表
CREATE TABLE IF NOT EXISTS weight_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '记录ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    weight DECIMAL(5,2) NOT NULL COMMENT '体重(kg)',
    record_date DATE NOT NULL COMMENT '记录日期',
    note VARCHAR(255) COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_user_date (user_id, record_date),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='体重记录表';

-- 目标体重表
CREATE TABLE IF NOT EXISTS weight_goal (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '目标ID',
    user_id BIGINT NOT NULL UNIQUE COMMENT '用户ID',
    target_weight DECIMAL(5,2) NOT NULL COMMENT '目标体重(kg)',
    target_date DATE COMMENT '目标达成日期',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='目标体重表';

-- 提醒记录表
CREATE TABLE IF NOT EXISTS reminder (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '提醒ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    reminder_time TIME NOT NULL COMMENT '提醒时间',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用 0-关闭 1-启用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_user_reminder (user_id),
    CONSTRAINT fk_reminder_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提醒记录表';

-- 初始化默认用户 admin/123456 (SHA256: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92)
INSERT INTO user (username, password, nickname, height) VALUES
('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '管理员', 170.00)
ON DUPLICATE KEY UPDATE username = username;
