dir=./downloads
max-concurrent-downloads=5
max-connection-per-server=16
split=16
min-split-size=10M
continue=true
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true
rpc-secret=
seed-ratio=1.0
seed-time=60
log=./aria2/aria2.log
log-level=info
daemon=false
enable-dht=true
enable-peer-exchange=true
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
bt-enable-lpd=true
bt-require-crypto=true
bt-detach-seed-only=true
auto-file-renaming=false
allow-overwrite=true
