import request from '@/utils/request'

export const login = (data) => request.post('/user/login', data)
export const register = (data) => request.post('/user/register', data)
export const getPublicTemplates = () => request.get('/template/public')
export const getUserTemplates = () => request.get('/template/my')
export const getTemplateItems = (id) => request.get(`/template/${id}/items`)
export const createTemplate = (data) => request.post('/template', data)
export const inheritTemplate = (parentId, data) => request.post(`/template/${parentId}/inherit`, data)
export const getUserItineraries = () => request.get('/itinerary/my')
export const createItinerary = (data) => request.post('/itinerary', data)
export const getItineraryItems = (id) => request.get(`/itinerary/${id}/items`)
export const addCustomItem = (id, data) => request.post(`/itinerary/${id}/items`, data)
export const checkItem = (itemId, checked) => request.put(`/itinerary/items/${itemId}/check`, { checked })
export const deleteItem = (itemId) => request.delete(`/itinerary/items/${itemId}`)
export const deleteItinerary = (id) => request.delete(`/itinerary/${id}`)
export const createShare = (data) => request.post('/share', data)
export const getShare = (code) => request.get(`/share/${code}`)
export const joinShare = (data) => request.post('/share/join', data)
export const getCategories = () => request.get('/category')
