import { Entity, Column, ManyToOne } from 'typeorm';
import { BaseEntity } from '../common/entities/base.entity';
import { User } from './user.entity';
import { ClassEntity } from './class.entity';
import { Subject } from './subject.entity';
import { ReportType } from '../common/types';

@Entity('learning_reports')
export class LearningReport extends BaseEntity {
  @Column({
    type: 'enum',
    enum: ReportType,
  })
  type: ReportType;

  @Column({
    name: 'student_id',
    type: 'bigint',
    unsigned: true,
    nullable: true,
  })
  studentId?: number;

  @Column({ name: 'class_id', type: 'bigint', unsigned: true, nullable: true })
  classId?: number;

  @Column({ name: 'subject_id', type: 'bigint', unsigned: true })
  subjectId: number;

  @Column({ name: 'period_start', type: 'date', nullable: true })
  periodStart?: Date;

  @Column({ name: 'period_end', type: 'date', nullable: true })
  periodEnd?: Date;

  @Column({ type: 'varchar', length: 200 })
  title: string;

  @Column({ type: 'text', nullable: true })
  summary?: string;

  @Column({ type: 'json' })
  content: any;

  @Column({
    name: 'overall_score',
    type: 'decimal',
    precision: 5,
    scale: 2,
    nullable: true,
  })
  overallScore?: number;

  @Column({ name: 'comparison_class_ids', type: 'json', nullable: true })
  comparisonClassIds?: any;

  @Column({
    name: 'creator_id',
    type: 'bigint',
    unsigned: true,
    nullable: true,
  })
  creatorId?: number;

  @Column({ name: 'is_auto_generated', type: 'tinyint', default: 1 })
  isAutoGenerated: number;

  @Column({ name: 'view_count', type: 'int', default: 0 })
  viewCount: number;

  @Column({ name: 'share_token', type: 'varchar', length: 100, nullable: true })
  shareToken?: string;

  @Column({ type: 'tinyint', default: 1 })
  status: number;

  @ManyToOne(() => User)
  student?: User;

  @ManyToOne(() => ClassEntity)
  class?: ClassEntity;

  @ManyToOne(() => Subject)
  subject: Subject;

  @ManyToOne(() => User)
  creator?: User;
}
